# Generated by Django 5.2.7 on 2026-01-05 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_capteur_created_at_alter_capteur_localisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesure',
            old_name='horodatage',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_to',
            new_name='assigne_a',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='capteur',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='titre',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='objet',
            field=models.CharField(default='Inconnu', max_length=200),
        ),
        migrations.AddField(
            model_name='capteur',
            name='seuil_max',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='capteur',
            name='seuil_min',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priorite',
            field=models.CharField(default='haute', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('assigné', 'Assigné'), ('en_cours', 'En cours'), ('clos', 'Clos')], default='ouvert', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='localisation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='capteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHT.capteur'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='capteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DHT.capteur'),
            preserve_default=False,
        ),
    ]
