# Generated by Django 5.2.7 on 2026-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_rename_horodatage_mesure_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='titre',
            field=models.CharField(default='Alerte', max_length=100),
        ),
    ]
