# Generated by Django 5.2.7 on 2026-01-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_ticket_description_ticket_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
